In [1]:
import numpy as np

In [20]:
input_data = np.array([[0,0,1],
                      [0,1,1],
                      [1,0,1],
                      [1,1,1]])

output_labels = np.array([[0],
                       [1],
                       [1],
                       [0]])

print(input_data)
print(output_labels)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [5]:
def activate(x, deriv = False):
    if(deriv ==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [34]:
np.random.seed(1)
synaptic_weight_0 = 2*np.random.random((3,4)) -1 
synaptic_weight_1 = 2*np.random.random((4,1)) -1
print(synaptic_weight_0)
print(synaptic_weight_1)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]


In [35]:
for j in range(60000):

    # Forward propagate through layers 0, 1, and 2# Forward 
    layer0 = input_data
    layer1 = activate(np.dot(layer0,synaptic_weight_0))
    layer2 = activate(np.dot(layer1,synaptic_weight_1))

    #calculate error for layer 2
    layer2_error = output_labels - layer2
    
    if (j % 10000) == 0:
        print("Error:" + str(np.mean(np.abs(layer2_error))))
        
    #Use it to compute the gradient
    layer2_gradient = layer2_error*activate(layer2,deriv=True)

    #calculate error for layer 1
    layer1_error = layer2_gradient.dot(synaptic_weight_1.T)
    
    #Use it to compute its gradient
    layer1_gradient = layer1_error * activate(layer1,deriv=True)
    
    #update the weights using the gradients
    synaptic_weight_1 += layer1.T.dot(layer2_gradient)
    synaptic_weight_0 += layer0.T.dot(layer1_gradient)

Error:0.496410031903
Error:0.00858452565325
Error:0.00578945986251
Error:0.00462917677677
Error:0.00395876528027
Error:0.00351012256786


In [36]:
print(layer2)

[[ 0.00260572]
 [ 0.99672209]
 [ 0.99701711]
 [ 0.00386759]]


In [41]:
a = np.array([[0,0,1]])

In [44]:
a.shape

(1, 3)

In [49]:
np.random.seed(1)
2*np.random.random((4,3)) -1 

array([[-0.16595599,  0.44064899, -0.99977125],
       [-0.39533485, -0.70648822, -0.81532281],
       [-0.62747958, -0.30887855, -0.20646505],
       [ 0.07763347, -0.16161097,  0.370439  ]])

In [60]:
activate(np.dot((2*np.random.random((1,4)) -1),
                activate(np.dot((2*np.random.random((4,3)) -1),
                                a.T))))

array([[ 0.52996499]])

In [62]:
activate(np.dot(activate(np.dot(a,
                                (2*np.random.random((3,4)) -1))),
               (2*np.random.random((4,1)) -1),))

array([[ 0.21186736]])

In [69]:
np.random.seed(1)
print(2*np.random.random((3,4)) -1)
np.dot(input_data,(2*np.random.random((3,4)) -1))

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]


array([[ 0.60148914,  0.93652315, -0.37315164,  0.38464523],
       [ 0.43609874,  1.05390281, -1.09237777, -0.21915179],
       [ 0.01039364,  1.69275802, -1.31837646,  0.72558025],
       [-0.15499676,  1.81013768, -2.03760258,  0.12178323]])

In [67]:
np.random.seed(1)
np.dot(a,(2*np.random.random((3,4)) -1))

array([[-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])